version: "2.1"

services:
  server:
    container_name: server
    command: npm run start:dev
    volumes:
      - ./:/app
    build: .
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "3000:3000"


  database:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_val:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'db_password'
      POSTGRES_USER: 'db_user'
      POSTGRES_DB: 'mydb'


volumes:
  user:
    driver: local
  db_val:
    driver: local
